#!/bin/bash -i

. urt-forever urt-game-guns "" "lib/urt4-api-server.run 8888 .
    +set com_hunkmegs 192
    +set dedicated 2
    +set net_enabled 7
    +set net_port 27960 +set net_port6 27960
    +set fs_basepath .
    +set fs_libpath .
    +set fs_homepath .
    +set sv_maxclients 20
    +set nodeurt_id pwnz-frag
    +set sv_hostname \"^3pwnz^5.pro ^1frag\"
    +set nodeurt_modes bomb ctf ctf.fun ctf.uz ffa ffa.unleash fun freeze ts ts.fun ts.uz
    +set nodeurt_mode ctf.fun
    +set nodeurt_discordchan 649944374381379584
    +exec server"
