#!/bin/bash -i

PIDFILE=/tmp/urt-engine-jump.pid

while [ true ]; do
  if [ -f $PIDFILE ]; then
    kill `cat $PIDFILE`
  fi

  sleep 1

  (
    cd $(dirname $0)

    set -m

    lib/urt4-api-server.run 8888 . \
      +set com_hunkmegs 512 \
      +set com_zonemegs 512 \
      +set dedicated 2 \
      +set net_port 1337 +set net_port6 1337 \
      +set fs_basepath . \
      +set fs_libpath . \
      +set fs_homepath . \
      +set sv_maxclients 24 \
      +set sv_hostname "^3pwnz^5.pro ^4jump" \
      +set nodeurt_modes jump \
      +set nodeurt_mode jump \
      +exec server \
      <&0 &echo $! > $PIDFILE

    PID=`cat $PIDFILE`
    fg
    wait $PID
    echo Process exited with $?
  )

  if [ ! -f $PIDFILE ]; then
    exit 0
  fi

  rm $PIDFILE
done
