#!/bin/bash

. urt-forever urt-game-jump "" "lib/urt4-api-server.run 8888 .
  +set com_hunkmegs 512
  +set com_zonemegs 512
  +set dedicated 2
  +set net_enabled 7
  +set net_port 1337 +set net_port6 1337
  +set fs_basepath .
  +set fs_libpath .
  +set fs_homepath .
  +set sv_maxclients 24
  +set nodeurt_id pwnz-jump
  +set sv_hostname \"^3pwnz^5.pro ^6jump\"
  +set nodeurt_modes jump
  +set nodeurt_mode jump
  +set nodeurt_discordchan 649944374381379584
  +exec server"
