#!/bin/bash -i

SCRIPT="$1"
PRE="$2"
EXEC="$3"

PIDFILE=/tmp/$SCRIPT.pid

while [ true ]; do
  if [ -f $PIDFILE ]; then
    kill `cat $PIDFILE`
  fi

  sleep 1

  (
    set -m

    $PRE
    $EXEC <&0 &echo $! > $PIDFILE
    PID=`cat $PIDFILE`

    int() {
      kill -INT $PID
    }

    trap int INT

    fg
    wait $PID
    echo Process exited with $?
  )

  if [ ! -f $PIDFILE ]; then
    exit 0
  fi

  rm $PIDFILE
  sleep 1
done
