#!/bin/sh
NAME="URT mod"
DIR=/home/urt/node-urt4
USER=urt
SCRIPT=urt-mod

setcap CAP_NET_BIND_SERVICE=+eip "$(readlink -f "$(which node)")"

export DISCORD_BOT_TOKEN="" # for discord integration
export GEOIP_ACCESS_KEY="" # for geo ip lookup integration

### BEGIN INIT INFO
# Provides:          urt-mod
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Starts URT mod.
### END INIT INFO

. "$DIR/urt-service"
